name: react-infinite-scroll-component

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        run: npm i

      - name: lint
        run: npm run lint

      - name: prettier
        run: npm run prettier:check

      - name: unit tests
        run: npm run test

      - name: ts type checks
        run: npm run ts-check

      - uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
